### ISSUE TITLE
代码所采用的OCR引擎？

### ISSUE THREAD

**Issue by entropy2333** [xueyongfu/chinese-layoutlm-v2#1]
您好，我最近在学习layouxlm，数据集中提供了字级别的OCR结果，能否请教一下代码中所采用的中文OCR引擎是什么？

**Comment by xueyongfu** [comment]
你好，XFUND是多语言的visual rich的文档数据集，里面有中文的数据，并且提供了字符集别的ocr识别结果。如果使用自己的数据集的话，可以把通用ocr的结果拆分字符级别，或者使用国内能够提供字符级别ocr的厂商

**Comment by entropy2333** [comment]
好的，我明白了，感谢您的回复！
