### ISSUE TITLE
关于 docx文件提取信息

### ISSUE THREAD

**Issue by hehuang139** [xueyongfu/chinese-layoutlm-v2#6]
您好，我想从word文档，比如一个很大的docx文件中提取信息，想向您请教下使用layoutLm模型能否实现信息提取，我看到的数据集很多都是来源于ocr的图片，么有直接使用docx做数据标注的

**Comment by xueyongfu** [comment]
可以直接在docx文档上直接标注，然后使用工具解析出text，text对应的bbox，还有人工标注的信息，最后还要把docx文档转成图片，这样模型训练所需要的数据集就准备完成了。

**Comment by hehuang139** [comment]
目前是否有docx标准的工具，因为我需要知道提取的信息在docx的哪个位置，比如说可能在docx中一个表单的字段上。这种是否能支持

**Comment by xueyongfu** [comment]
支持的，可以去调研一下这方面的python工具，挺多的

**Comment by hehuang139** [comment]
是否一定要先转图片？对于layoutLm这个模型，

**Comment by xueyongfu** [comment]
不需要的，图片是最后转的

**Comment by hehuang139** [comment]
感谢！
