### ISSUE TITLE
关于实体识别训练数据的问题

### ISSUE THREAD

**Issue by buaashn** [xueyongfu/chinese-layoutlm-v2#9]
您好，我目前获取到一些orc识别后的json数据，并且编写代码格式化，与训练集中的json数据格式相同。但是我没有原始图像，也就是.zip文件，还可以使用该模型训练和识别吗

**Comment by xueyongfu** [comment]
该模型需要输入text，layout，image三个模态的特征，所以是没有原始图像是用不了的。
但是可以使用这篇paper开源的模型，该模型只需要输入text、layout特征，不需要image特征，并且也获得了不错的效果。
paper：LiLT: A Simple yet Effective Language-Independent Layout Transformer for Structured Document Understanding
github：https://github.com/jpWang/LiLT

**Comment by buaashn** [comment]
我研究一下，非常感谢
